// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC33vTchBakWLp70zaOdT8Vk0PXrS4F1mY',
    appId: '1:850547521285:web:c0aa94535eb482dc90696c',
    messagingSenderId: '850547521285',
    projectId: 'wineapp-e5339',
    authDomain: 'wineapp-e5339.firebaseapp.com',
    storageBucket: 'wineapp-e5339.firebasestorage.app',
    measurementId: 'G-V9JKR147ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaR_ZA2TwNHr-o_DHB4QlMBGkyZUrVeCw',
    appId: '1:850547521285:android:50edcf818d58c87190696c',
    messagingSenderId: '850547521285',
    projectId: 'wineapp-e5339',
    storageBucket: 'wineapp-e5339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC44FUDpf5U9abVV_HQCic4fowx0yi9-2Y',
    appId: '1:850547521285:ios:c844ce026d39092b90696c',
    messagingSenderId: '850547521285',
    projectId: 'wineapp-e5339',
    storageBucket: 'wineapp-e5339.firebasestorage.app',
    iosBundleId: 'com.example.wineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC44FUDpf5U9abVV_HQCic4fowx0yi9-2Y',
    appId: '1:850547521285:ios:c844ce026d39092b90696c',
    messagingSenderId: '850547521285',
    projectId: 'wineapp-e5339',
    storageBucket: 'wineapp-e5339.firebasestorage.app',
    iosBundleId: 'com.example.wineApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC33vTchBakWLp70zaOdT8Vk0PXrS4F1mY',
    appId: '1:850547521285:web:68e196327111703490696c',
    messagingSenderId: '850547521285',
    projectId: 'wineapp-e5339',
    authDomain: 'wineapp-e5339.firebaseapp.com',
    storageBucket: 'wineapp-e5339.firebasestorage.app',
    measurementId: 'G-646B83C21Z',
  );
}
